schema = 3

[mod]
  [mod."github.com/fogleman/gg"]
    version = "v1.3.0"
    hash = "sha256-Fs2JI0FmF4N5EzXJzGAPZMxZxo6wKyebkN/iBZ9sdNo="
  [mod."github.com/goccy/go-graphviz"]
    version = "v0.0.9"
    hash = "sha256-yMrouwBgJH58YtDq76zxLGZoE52nsqZn2p6s/vBZp00="
  [mod."github.com/golang/freetype"]
    version = "v0.0.0-20170609003504-e2365dfdc4a0"
    hash = "sha256-AHAFBd20/tqxohkWyQkui2bUef9i1HWYgk9LOIFErvA="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20200119044424-58c23975cae1"
    hash = "sha256-vdQsJfeRzmOWnvf2U0B3X4/rAM7b6G5YZE4HluMTV0Q="
